docs/iframes-and-alerts.rst
...than name.
The implementation of get_iframe(name) should probably be updated so it doesn't imply that only name can be used.
=> Update to indicate that get_iframe() can be used with other attributes..

docs/drivers/zope.testbrowser.rst, splinter/driver/zopetestbrowser.py
Otherwise there was no possibility to tell the mechanize browser that is used by the zope.testbrowser driver to ignore robots.txt
=> added ignore_robots flag to zope.testbrowser

setup.py
Newer firefox versions often break with older selenium.
=> Use a minimum selenium version; easier to update selenium in parent packages.

splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/webdriver/__init__.py, tests/base.py, tests/click_elements.py, tests/form_elements.py, tests/test_browser.py, tests/test_djangoclient.py, tests/test_flaskclient.py, tests/test_webdriver_chrome.py, tests/test_webdriver_firefox.py, tests/test_zopetestbrowser.py
See discussion on #165 - this essentially takes the inverse approach to #304 so that titles and html source are text strings rather than byte strings which makes writing tests feel much more natural.
=> Return decoded text strings for title and html.

splinter/driver/webdriver/__init__.py, tests/base.py
With select option lists, it is more convenient to select them by their
(visible) text.
Let me know if you find this useful, and I will add tests.
=> Add `select_by_text` methods

docs/tutorial.rst
The link http://splinter.readthedocs.org/docs/install.html gives a 404
=> docs: fix broken link to install page on tutorial page

splinter/driver/webdriver/remote.py
I've been monkey patching this in for a while and it works with Chrome running on Sauce Labs at least.
=> Enable cookie support for remote webdriver

splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/lxmldriver.py
There's a lot of repetition in the Flask and Django clients. In preparation for allowing html5lib to be used in place of libxml2 (https://github.com/cobrateam/splinter/issues/441) I thought these should be merged. I'm a bit confused as to why so much code was just copied and pasted in the first place?
=> Fix repetition in flask and django clients

splinter/driver/lxmldriver.py, tests/static/index.html, tests/test_flaskclient.py
As initially described in #428, we need multi-select support for Flask (i.e. `<select multiple>`). In this PR:
- Added test for serializing a form for a select with multiple values
- Added `serialize` method for testing serialization exclusively
- Added fix for `fill_form` to support accepting multiple values
**Missing:**
- Test for `fill_form` with list coercion. I am not sure why my past self never wrote a test for that
=> Added multi-select support to LxmlDriver

splinter/driver/flaskclient.py, tests/test_flaskclient.py
In our test suite, we need to send a HTML-specific `Accept` header in order to differentiate HTML requests from JSON ones. In order to add support for that, we need custom headers from `splinter's Flask` client. In this PR:
- Added custom header support for Flask client (based off of Django client)
- Added test
**Notes:**
For anyone who wants `0.7.3` compatible support, we wrote that out here:
https://github.com/underdogio/splinter/compare/6993e85...underdogio:e7b81e5
=> Added custom headers support to Flask client

splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/webdriver/cookie_manager.py, splinter/driver/zopetestbrowser.py, tests/cookies.py
During our tests, we wanted to assert some cookies were not present. However, `flaskclient` was erroring out since it was accessing a key that didn't exist via `__getitem__`. As documented by `__contains__`, `__getitem__` is invoked when `__contains__` isn't defined.
https://docs.python.org/2/reference/datamodel.html#object.__contains__
```python
self.assertIn('a', browser.cookies)
self.assertNotIn('b', browser.cookies)
```
To remedy that, we wrote out `__contains__` for each of our engines. In this PR:
- Added `in`/`not in` support for cookies via `__contains__`
- Added test
=> Added support for `in` against cookies

README.rst
These are alternatives to lettuce that are more actively maintained, which I use with splinter.
=> add link to behave-django and behave

docs/index.rst, splinter/driver/element_present.py, splinter/driver/lxmldriver.py, splinter/driver/zopetestbrowser.py, tests/is_element_present_nojs.py, tests/test_djangoclient.py, tests/test_flaskclient.py, tests/test_zopetestbrowser.py
In order to bring more compatibility between javascript and non-javascript drivers I have implemented missing is_element_present_by_* methods. Although those methods are supposed to be used for dynamically appearing elements on page they are convenient also for static elements. I thing it is worth including them for non-javascript drivers. We have already is_text_present in non-javascript drivers.
Implemented methods will raise NotImplementedError if someone try to use wait_time, as it has not sense to use it in non-javascript drivers. I'm not really sure is it expected behavior. My thinking was that it is better to clearly communicate for user that it's not supported and make him catch error and do what he thing is suitable then force him to debug why it doesn't wait for loading.
=> Support for is_element_present_by_* in non-javascript drivers.

splinter/driver/flaskclient.py, tests/base.py, tests/fake_webapp.py, tests/test_djangoclient.py
I have moved redirection test to base as it should work exactly the same in all drivers.
For flask, redirection have to be done in driver because flask doesn't expose redirection chain yet. It can be dropped (and probably integrated with django driver) once flask will expose it.
=> Consistent redirects behaviour

splinter/driver/webdriver/__init__.py, tests/form_elements.py
Clears text field types if they already have values in them
`browser.find_by_name('telephone').clear()`
`browser.find_by_tag('textarea').clear()`
`browser.find_by_id('username').clear()`
=> Webdriver support for clearing text field types

README.rst, docs/_templates/layout.html, docs/browser.rst, docs/drivers/remote.rst, docs/matchers.rst, splinter/driver/__init__.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

docs/drivers/chrome.rst, splinter/driver/webdriver/chrome.py
My use case was to enable the device emulation mode in Chrome.
Not much of a technical change, some more doc.
=> allow to pass a chrome Options instance to Browser

docs/elements-in-the-page.rst, splinter/driver/__init__.py, tests/click_elements.py, tests/static/index.html
=> Adding method click_link_by_id

splinter/driver/webdriver/__init__.py
Currently every taken screenshot file stays opened until python process is closed, which prevents removing it (on Windows)
=> Don't hold a screenshot file opened

splinter/driver/webdriver/firefox.py
Currently there's no straightforward way to specify the timeout for the Firefox webdriver. 
Selenium's default value (30) is too short for low-performance settings, so it would be desirable to not only have a larger timeout window (this PR sets it to 90) as well as letting the user define this when instantiating the webdriver.
=> Enable timeout setting for Firefox webdriver

splinter/driver/lxmldriver.py, tests/form_elements.py, tests/static/index.html
Previously, `find_by_xpath()` (or `find_by_tag()`, etc.) would not consider a `<textarea>` a "control element", and would return it as an `LxmlElement`, which can't be `fill()`d. This (should) make it so that all `find_by_*` methods treat `<textarea>`s the same.
=> consider a <textarea> a control element

splinter/driver/__init__.py
I was surprised to find that passing `slowly=True` changes the function's behavior so that it doesn't perform the action directly, but instead returns an iterator. Hopefully this will help keep others from being surprised.
=> Document behavior of `slowly=True` in `type()`

splinter/driver/webdriver/firefox.py
To be able to specify `firefox_binary` and `executable_path`.
See https://github.com/SeleniumHQ/selenium/blob/b94c9021aa40c12494cd3f88f7c2220af79f8b41/py/selenium/webdriver/firefox/webdriver.py#L55 from the Selenium 3.1.0 release commit.
=> Take in **kwargs for Firefox to pass them on to Selenium

docs/drivers/chrome.rst, docs/index.rst, splinter/driver/webdriver/chrome.py
Starting with Chrome 59, Google has implemented a headless option. 
As you all know, PhantomJS will no longer be supported as the project lead stepped down.
More infos here:
https://developers.google.com/web/updates/2017/04/headless-chrome
Regards,
Dan
=> Headless option for chrome

docs/drivers/remote.rst
I ran into not knowing exactly what the URL should be. After checking the Saucelabs docs I found out, might be handy to just have it in here.
=> Add example remote URL for Saucelabs

docs/drivers/chrome.rst
The given URL to the chrome driver for windows seemed to be orphan. Added the "official" URL to the chrome driver, which I found to be working.
=> Chrome driver download source seems to be invalid

splinter/driver/__init__.py, splinter/driver/lxmldriver.py, splinter/driver/webdriver/__init__.py, splinter/driver/zopetestbrowser.py, tests/form_elements.py, tests/static/index.html
Current implementation for `fill_form` attempts to find fields by their names.
However, if the same name is found in multiple places, this method will either
fail with a `InvalidElementStateException` exception or the wrong field may be
filled.
Please see #564 for more info.
=> Make `fill_form` more robust by requiring form ID.

splinter/driver/webdriver/__init__.py, tests/base.py
As described in #584, webdriver.execute_script should relay any return value from the underlying `driver.execute_script` call.
=> Allow return value for execute_script to be returned. Fixes #584.

splinter/driver/webdriver/chrome.py
'options' are replaced by 'chrome_options' in Selenium's Chrome webdriver.
See https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/chrome/webdriver.py#L50-L51
```
if chrome_options:
warnings.warn('use options instead of chrome_options', DeprecationWarning)
options = chrome_options
```
=> Pass 'options' instead of 'chrome_options'

docs/drivers/chrome.rst
Referencing Windows XP instructions might alarm some people and give the impression they have found a legacy repo. Although the URL is not an official Windows page I believe it holds the information needed. I would suggest moving the information to the wiki in the future.
=> Windows Variables Suggestions

splinter/driver/__init__.py
one letter typo in splinter/driver/__init__.py
=> fix docstring typo in splinter.driver

splinter/driver/webdriver/__init__.py
I don't know how to test this -- especially since I can't duplicate the problem all the time.  I just know that the monkey-patched version I am running has not yet raised this error and continues to work.
I'm happy to make modifications (including adding tests) with some guidance.
=> Check for StaleElementReferenceException

splinter/driver/webdriver/firefox.py
Fixes:
> DeprecationWarning: use options instead of firefox_options
=> firefox: fix DeprecationWarning with firefox_options

.travis.yml
In this [travis report](https://github.com/travis-ci/travis-ci/issues/9815), is a fix to the error with python 3.7. This PR apply this fix in splinter.
=> Fix travis config for python 3.7

README.rst, docs/tutorial.rst
This pull request addresses issue #487 
Updated tutorial to highlight that the `Browser` function defaults to Firefox if there are no arguments.
Added the same note to the readme.
=> Update tutorial and readme

splinter/driver/webdriver/__init__.py
The syntax for switch to alert has changed from
`switch_to.alert()` to `switch_to_alert()`, updated webdriver init to reflect this change.
=> Update switch to alert

doc-requirements.txt, docs/browser.rst, docs/community.rst, docs/contribute.rst, docs/drivers/chrome.rst, docs/drivers/django.rst, docs/drivers/firefox.rst, docs/index.rst, docs/screenshot.rst, docs/why.rst
Before, the full TOC was not available in the sidebar, so if you clicked on a link to the Installation page (for example), you would have to navigate back to Home to get to any other page. I updated  doc-requirements.txt to use the latest Read the Docs theme, which allows for captions in the TOC. Then, I put a few toctree directives in index.rst so that the full TOC would appear in the sidebar, with captions separating the different categories.
I also made various language edits for clarity, grammar, and punctuation.
Finally, Sphinx was throwing some warnings about title underlines being too short. I don't think they affected the build, but they were extra noise within legitimate warnings, so I made those underlines longer to get rid of the warnings.
=> Made full TOC appear in sidebar for better navigation. Various language edits.

setup.py
Commit dcfba0ea808dda8224d2f52e64f099a2bbf2b5f8 started using the six
module in splinter/driver/webdriver/__init__.py, but did not declare
the dependency in setup.py as it should have.
Fixes #671.
=> setup.py: add six to install_requires

splinter/driver/webdriver/__init__.py
```
=== warnings summary =====================================================
.../splinter/driver/webdriver/__init__.py:305:
DeprecationWarning: use driver.switch_to.alert instead
return AlertElement(self.driver.switch_to_alert())
=======================================================================
```
See the docs: https://selenium-python.readthedocs.io/api.html?highlight=switch_to#selenium.webdriver.remote.webdriver.WebDriver.switch_to_alert
=> Use 'switch_to.alert' instead of deprecated 'switch_to_alert'

tests/form_elements.py
In Chrome, the default value for an `input type="submit` is "Submit". However in Firefox its "Submit Query".
=> Fix test_clicking_submit_input_posts_empty_value_if_value_not_present

tests/test_webdriver_firefox.py
acceptSslCerts has been deprecated in favour of acceptInsecureCerts. However, the current implementation of webdriver will always override a desired capability in favour of an Options value, and the default Options object has this value set to a true value.
=> Fix test_capabilities_set. 

tests/fake_django/urls.py
This should enable to normally run tests for django2
Always red tests are bad)
=> Fix tests failures due to django2 compatibilty

splinter/driver/webdriver/__init__.py, tests/fake_webapp.py, tests/mouse_interaction.py, tests/static/mouse.html, tests/test_webdriver_remote.py
Changes the behaviour of the mouse_out() method to move to (-10, -10) relative to the top left of the element.
+ Add a new test where the hovered element is at the top-left of the browser window.
This fixes the mouse_out behaviour in Chrome.
=> Fix mouse_out method

tests/test_webdriver_chrome.py
Convert the bytes object into a string for python 3.6+ compatibility.
=> Fix test_webdriver_chrome test_attach_file

tests/popups.py
Some tests fail in Chrome due to a leftover popup window from a previous test.
The reason appears to be that if a popup window is already open, each browser has different behaviour when opening a new popup after a URL redirection.
- Chrome: A new window is opened.
- Firefox: The existing popup window is used.
This can be reproduced manually using the example app:
Steps to Reproduce:
1 - Run the example app and go to localhost:5000
2 - Open a popup window
3 - Navigate to google.com
4 - Navigate to localhost:5000 (Do not use a back button)
5 - Open a popup window
=> Fix popups tests

docs/iframes-and-alerts.rst, splinter/driver/webdriver/__init__.py
- Remove `fill_with` method, since it just wraps `send_keys`
The purpose of this PR is to change Browser.get_alert() such that it provides access to the real selenium Alert object instead of a wrapper. The context manager functionality has been preserved.
=> Browser.get_alert() returns Alert instead of a wrapper object

splinter/driver/webdriver/__init__.py
Fixes #419 and #575
This adds the `find_link_by` functionality to elements in the form of Element.links.find_by_
The Browser behaves the same way, ie: `Browser.links.find_by_href` however the original API is preserved. `Browser.find_link_by_href` still works.
If this PR is accepted, I'll follow it up with changing the documentation and adding a deprecation notice for the Browser.find_link_by methods.
If the API change is rejected, I'll add the older method names to the Element. Regardless, I think this pattern of using a parent object, even if hidden, still reduces code duplication.
=> Change find_link_by API and add functionality to Elements

splinter/element_list.py, tests/test_element_list.py
When elements aren't found on the page, calling methods like ElementList.click() didn't raise this error. Instead it would report "AttributeError: 'ElementList' object has no attribute 'click'" which confuses users to look at other places than the actual error.
=> Fix ElementList.__getattr__() to no longer hide ElementNotFound

splinter/driver/webdriver/firefox.py
This commit fixes Firefox headless mode so that it respects the possible `firefox_binary` option.
Previously a custom Firefox path string or browser object passed in `kwargs['firefox_binary']` would not work in headless mode. Instead the option was silently overwritten and a default executable location was used.
=> Fix Firefox headless mode to handle custom firefox_binary option

splinter/driver/webdriver/firefox.py, tests/test_webdriver_firefox.py
This commit clears the `MOZ_HEADLESS` environment variable explicitly when the `headless` option is not set. Selenium passes the environment variables to Firefox as they are, and the environment variable alone is enough to cause a headless launch.
Previously a single headless launch would cause all subsequent launches be headless regardless the option being set or not.
=> Fix Firefox driver to respect headless option in subsequent calls

splinter/driver/webdriver/__init__.py, tests/base.py
A fix for issue #387. Have `browser.get_alert()` return `None` if no alert exists, instead of Selenium exception.
=> Browser.get_alert() returns None if no alert exists

docs/matchers.rst
#712 Adds documentation for the two cases ( `css`,`xpath`) of `is_element_visible` in [Matchers](https://splinter.readthedocs.io/en/latest/matchers.html) page. 
Please let me know if I missed something.
=> added docs for is_element_visible methods

README.rst, docs/community.rst
Some of the external links had either moved to new addresses or just gone completely. Changed to the correct URLS and removed those who didn't exist anymore.
=> Fixed dead external links

docs/drivers/remote.rst, splinter/driver/webdriver/remote.py
This changes the Remote Browser from accepting desired capabilities in the keyword args to accepting anything and sending to Remote Webdriver as keyword args. As a result, desired capabilities are now sent as a dictionary instead of keyword args.
Documentation updated to reflect the new behaviour.
=> Accept all valid arguments for Remote WebDriver

splinter/driver/webdriver/remote.py, tests/test_webdriver_remote.py, travis-install.bash
Newer versions of Remote Firefox support ActionChains.
This also deals with most of #674.
However, there's still no specific test configuration for Remote Chrome.
=> Allow ActionChains when using Remote WebDriver

splinter/browser.py, splinter/driver/webdriver/remote.py, splinter/driver/webdriver/remote_connection.py
Shamelessly pulled from the pytest-splinter project. These patches add some much needed stability to Remote WebDriver runs, especially when running tests in parallel.
Personally, these sorts of things make more sense as part of Splinter than as part of an external pytest plugin. As another benefit, they also make running Splinter's own tests in parallel more stable.
=> Patch Remote WebDriver to add retry attempts. Add retry to Browser init.

splinter/driver/webdriver/__init__.py
This fixes an issue where mouse interaction fails on nested elements. The `parent` attribute of a nested WebDriverElement is another WebDriverElement, which has no driver attribute.
ie: 
```
x = browser.find_by_xpath('...')
y = x.find_by_xpath('...')
y.double_click()
```
=> Add driver attribute to WebDriverElement

.travis.yml, tests/test_webdriver.py, tests/test_webdriver_chrome.py, tests/test_webdriver_firefox.py, tests/test_webdriver_remote.py, travis-install.bash
This PR reduces some code duplication by using pytest's parametrize feature, as opposed to placing tests in classes.
Some tests have been rewritten slightly to use pytest, and test_flaskclient.py, test_browser.py test_element_list.py, and test_request_handler.py have been combined into one job on travis-CI.
=> Refactor some chrome/firefox tests to use pytest

splinter/driver/webdriver/__init__.py, tests/is_element_present.py
#732 Did not actually cause the is_element_not_x functions to return immediately after nothing is found. The 0 second wait time was overridden by the global wait_time.
This PR changes things in such a way that 0 seconds for wait_time will cause find_by to only search once, instead of polling.
The _find() function will run once if 0 seconds is the wait_time, else it will run in a while loop until timeout.
=> find_by with 0 second wait_time only checks once

splinter/driver/flaskclient.py, tests/fake_webapp.py, tests/static/index.html, tests/test_flaskclient.py
This is another attempt at getting a fix for cobrateam/splinter#515 by @anthonyjb merged into splinter; I've added some tests but otherwise this is basically a copy of #517.
=> Fix FlaskClient redirects

splinter/driver/lxmldriver.py, splinter/driver/webdriver/__init__.py, splinter/driver/zopetestbrowser.py, tests/find_elements.py, tests/static/index.html
=> make find_by_value works with btn elements

splinter/browser.py, tests/test_browser.py
Addresses the error message seen in: #748
=> Fix: Incorrect error thrown when missing chrome/geckodriver

.travis.yml, tests/base.py, tests/static/alert.html
Newer versions of firefox and selenium don't play nicely when alerts are spammed.
=> Unit tests no longer fail on latest firefox version

.travis.yml, splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/webdriver/cookie_manager.py, splinter/driver/zopetestbrowser.py, test-requirements.txt, tests/base.py, tests/cookies.py, tests/popups.py, travis-install.bash
- Run chrome and firefox tests in parallel. Shaves a couple of minutes off running everything.
- Rewrite cookie tests to use unique browser instances and use pytest asserts.
- Tweak popup test to not rely on state from previous test.
- Found a bug in CookieManager while trying to get the tests to run in parallel. Running everything in one browser window created false negatives.
=> Fix cookies test to be able to run in parallel. Fix bug with adding multiple cookies from list.

test-requirements.txt
From the [Travis CI test output](https://travis-ci.org/github/cobrateam/splinter/jobs/717256569#L463-L465)...
```
.tox/python/lib/python3.8/site-packages/lxml/html/_setmixin.py:1
/home/travis/build/cobrateam/splinter/.tox/python/lib/python3.8/site-packages/lxml/html/_setmixin.py:1:
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is
deprecated since Python 3.3, and in 3.9 it will stop working
from collections import MutableSet
```
=> test-requirements.txt: Upgrade lxml for Python 3.9

tests/base.py, tests/cookies.py, tests/popups.py
Fixes #792
Rewrites the popups tests to use pytest asserts instead of unittest functions
=> Fix flaky unit tests by using unique browser instances

splinter/cookie_manager.py, splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/webdriver/cookie_manager.py, splinter/driver/zopetestbrowser.py
Creates a standard call for deleting all cookies.
=> Add delete_all method to CookieManager

splinter/browser.py, tests/test_browser.py
It looks like Browser is taking `retry_count` as an argument
which is never used. Fixed by adding it to get_driver.
=> Added retry_count to get_driver

.travis.yml, setup.py
We haven't tested 3.3, 3.4 or 3.5 in years, may as well remove them officially. 3.9.0 released in October 2020, so it seems a good time to add it.
=> Remove python 3.3, 3.4, 3.5 from setup.py, add 3.9. Add 3.9 to CI jobs

docs/drivers/chrome.rst
`brew cask install chromedriver` no longer works. See here https://github.com/Homebrew/discussions/discussions/902#discussioncomment-398348
Also, I just tried `brew install chromedriver` and that works too. No cask required!
=> Updated doc for Mac os

splinter/cookie_manager.py, splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/webdriver/cookie_manager.py, splinter/driver/zopetestbrowser.py, tests/cookies.py
Adding cookies with a list, eg:
```
my_list = [{...}, {...}]
CookieManager.add(my_list)
```
has always been undocumented.  Having an argument that takes multiple types seems like a bad idea. If a user really wants to add multiple cookies, it's more likely they're doing:
```
for c in cookies:
CookieManager.add(c)
```
=> Remove sending a list of cookie dicts to CookieManager.add()

splinter/cookie_manager.py, splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/webdriver/cookie_manager.py, splinter/driver/zopetestbrowser.py, tests/cookies.py, tests/test_djangoclient.py, tests/test_flaskclient.py, tests/test_zopetestbrowser.py
The goal of this PR is to allow cookies to be created with whatever arguments the driver accepts. Fixes #388
=> Accept extra arguments for cookies

.github/workflows/windows.yml, docs/drivers/edge.rst, docs/index.rst, requirements/doc.txt, requirements/test_windows.txt, setup.py, splinter/browser.py, splinter/driver/webdriver/edge.py, tests/base.py, tests/fake_webapp.py, tests/test_popups.py, tests/test_webdriver.py, tests/test_webdriver_edge_chromium.py, tox.ini
- Separate Github Actions Workflow for running Edge tests on Windows.
- Use Microsoft's implementation of Edge WebDriver for Selenium 3 compatibility.
- Edge Legacy is untested, but available to toggle on since Selenium supports it.
=> Add support for Microsoft Edge

splinter/driver/webdriver/chrome.py, splinter/driver/webdriver/firefox.py
This change matches what's in chrome.py#L28 to allow passing in options when
creating a new Browser() window. Also renamed variable from `firefox_options` to
just `options` to make it generic to match chrome.py.
```
from selenium.webdriver import Firefox, FirefoxOptions
opts = FirefoxOptions()
opts.add_argument("--some-argument")
browser = Browser('firefox', options=opts)
```
=> allow passing options to Firefox webdriver

.github/workflows/main.yml, .github/workflows/windows.yml, requirements/lint.txt, requirements/test.txt, requirements/test_windows.txt, setup.py, splinter/browser.py, splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/lxmldriver.py, splinter/driver/webdriver/__init__.py, splinter/driver/webdriver/remote_connection.py, tests/base.py, tests/conftest.py, tests/fake_django/urls.py, tests/test_browser.py, tests/test_djangoclient.py, tests/test_webdriver_remote.py, tests/test_zopetestbrowser.py
It's time.
- Python 2.7 has been pining for the fjords for almost 2 years.
- According to pypistats, only around 8% of downloads are from 2.7 users.
- Selenium 4 isn't compatible with Python 2.7
=> Remove python 2.7 support

splinter/driver/webdriver/__init__.py, splinter/driver/webdriver/chrome.py, splinter/driver/webdriver/edge.py, splinter/driver/webdriver/firefox.py, splinter/driver/webdriver/remote.py
This PR simplifies how the Chrome, Firefox, and Remote classes inherit from BaseWebDriver. It is now possible to use BaseWebDriver directly.
This does not impact the ability to override element_class or _cookie_manager in the future, if necessary.
=> Allow BaseWebDriver to be used directly

requirements/lint.txt
mccabe is a dependency of flake8, no need to specify separately.
=> Remove mccabe from requirements

.github/workflows/upload-to-pypi.yml, Makefile
This will happen automatically when we tag the repo.
TODO:
=> github/workflows: add workflow for uploading to PyPI

.github/workflows/upload-to-pypi.yml
=> github/workflows/upload-to-pypi: install wheel

.github/workflows/main.yml
The previous code wasn't doing the right thing: it started the server in
background, slept for 3 seconds in background and started the tests.
Adding another `&` after `sleep 3` would make it actually wait 3
seconds, but instead of doing that we use `timeout` and try the
healthcheck endpoint until the server is ready.
Also upgrade selenium-server.
=> github/workflows: fix selenium-server flakiness

docs/news/0.18.1.rst, docs/news/0.9.0.rst, splinter/driver/flaskclient.py, tests/is_text_present.py
There are small typos in:
- docs/news/0.18.1.rst
- docs/news/0.9.0.rst
- splinter/driver/flaskclient.py
- tests/is_text_present.py
Fixes:
- Should read `support` rather than `suport`.
- Should read `received` rather than `recieved`.
- Should read `present` rather than `prasent`.
- Should read `*clobbering*` rather than `clobbing`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

splinter/driver/flaskclient.py, tests/fake_webapp.py
I recently opened an issue #1080 . When we try to redirect the user to another page, after having sent a file through the form. The following error occurs:
```
ValueError: read of closed file
```
This happens, because, to redirect user for another page using some test client is necessary  ensure that to `GET` the `data` object is not sent.
=> Fix attach_file method to FlaskClient

.github/workflows/main.yml, .github/workflows/windows.yml, docs/drivers/edge.rst, docs/install/driver_install.rst, docs/install/install.rst, setup.py, splinter/driver/webdriver/edge.py, tox.ini
The Selenium 3.x series is very dead at this point. For a while it made sense to support it because:
- Selenium 4.0 had deprecation warnings as opposed to removals.
- Splinter did not have to write very much custom code to handle both 3.x and 4.x
Selenium 4.x is moving past these deprecation warnings and it's not worth it to maintain both as a back-end for Splinter as Selenium 4.x continues diverging. At this point, anyone who absolutely needs Selenium 3.x will have to make do with Splinter 0.19.0.
=> Remove selenium 3 support

requirements/test.txt
This should "fix" the flaskclient driver. Actual fix would be to change the call site for the cookie stuff. We can do that next (as part of #1159, maybe).
=> requirements/test: pin werkzeug

.github/workflows/main.yml, .github/workflows/windows.yml, setup.py
Python 3.7 has reached end of life, let's remove it from CI and from setup.py.
=> Remove Python 3.7

docs/drivers/remote.rst
=> docs/drivers/remote: fix desired capabilities

splinter/config.py
In Splinter 0.20.0 was introduced `splinter.config.Config` which has `user_agent = ''`
It leads to empty string of User Agent in a browser. As result any applicaiton which checks User-Agent think the browser is invalid.
I tried it with Standalone Cromium 117 in docker. 
`driver.execute_script("return navigator.userAgent")` will return `''` instead of `'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'`
=> Make User Agent None by default

splinter/driver/webdriver/chrome.py, splinter/driver/webdriver/edge.py, splinter/driver/webdriver/firefox.py
Remove the deprecation warning and handler for the executable_path argument. It's been about a year and the documentation has already been updated.
=> Remove deprecation warning

docs/conf.py, requirements/doc.txt
Compared to the RTD theme, the immaterial theme has cleaner formatting and a dark mode for free. It's popular so we may as well buy in. This PR also fixes a break that happened at some point where the docs hosted on readthedocs did not use the correct theme.
=> Replace documentation theme

splinter/driver/__init__.py, splinter/driver/lxmldriver.py, splinter/driver/webdriver/__init__.py, splinter/driver/zopetestbrowser.py
Solution for:
#8
#162
#684
This PR adds a generic find method to replace the browser level actions. Currently it uses name, so the following are equivalent:
```
browser.fill('v', 'my_text')
```
```
browser.find('v').fill('my_text')
```
In 2021, find_by_name is significantly less useful than css or xpath. By exposing a generic find with an API for controlling which strategy is used, the browser level methods become unnecessary, but the shorthand style of writing scripts is preserved and made relevant for more people, eg:
```
browser.set_find_strategy('css')
browser.find('.my_css').click()
browser.find('.another_css').fill('some_text')
```
This also removes any need to deprecate find_by_x methods.
Roadmap:
#933
- Deprecate browser level actions
- Add generic find() method, defaults to …
=> Deprecate browser-level fill(), type(), check(), uncheck()

splinter/driver/webdriver/__init__.py, splinter/retry.py
- Rewrite `_find` to only handle the Selenium actions.
- Rewrite `find_by` to use the generic `_retry` function.
- Rewrite the `_retry` function to return the result of the function instead of a bool.
=> Start using a generic retry function

splinter/abc/__init__.py, splinter/abc/cookie_manager.py, splinter/driver/__init__.py, splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/webdriver/cookie_manager.py, splinter/driver/zopetestbrowser.py
This PR:
- Adds the `__contains__` method to the CookieManagerAPI interface
- Uses the ABC module to enforce the Splinter API 
Using ABC as a base class has some advantages for creating interfaces. The abstractmethod decorator forces subclasses to implement the decorated methods. Eventually, I'd like to have DriverAPI and ElementAPI use ABC as a base class.
=> Use ABC for CookieManagerAPI

.github/workflows/main.yml, tests/conftest.py, tests/test_webdriver_chrome.py, tests/test_webdriver_edge_chromium.py, tests/test_webdriver_firefox.py, tests/tests_firefox_webdriver/test_firefox_capabilities.py, tests/tests_firefox_webdriver/test_firefox_extension.py, tests/tests_firefox_webdriver/test_firefox_preferences.py, tests/tests_webdriver/test_async_finder.py, tests/tests_webdriver/test_element_is_visible.py, tests/tests_webdriver/test_html_snapshot.py, tests/tests_webdriver/test_iframes.py, tests/tests_webdriver/test_mouse_interaction.py, tests/tests_webdriver/test_popups.py, tests/tests_webdriver/test_screenshot.py, tests/tests_webdriver/test_shadow_root.py, tests/tests_webdriver/test_webdriver.py, tox.ini
This PR adds:
- A command line option for setting the browser name when running our test suite. 
- A pytest fixture for the browser and browser configuration which consumes the command line option
Doing so allows us to resolve the browser's name on a per-job basis instead of on each individual test.
=> Use pytest fixtures to setup browser, split up chrome and firefox jobs

.github/workflows/windows.yml, tests/conftest.py, tox.ini
- Ensure disable-dev-shm-usage is set for chromium
- Retry failing tests
=> tests: Try to stabilize Edge tests
