docs/finding.rst, docs/matchers.rst, splinter/driver/__init__.py, splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/webdriver/__init__.py, splinter/driver/zopetestbrowser.py, tests/find_elements.py, tests/is_element_present.py
In #274, there was a discussion about adding `find_by_text`.
This PR adds that.
=> Add finding by text.

setup.py
It's useful to link from the pypi page to github
=> Add package url in setup.py

docs/drivers/firefox.rst, splinter/driver/webdriver/firefox.py, tests/test_webdriver_firefox.py
I would like to pass some writable capabilities to the wrapped selenium driver. I've only added it for firefox because I didn't really want to try to make a big change as a first-time contributor.
=> Added selenium capabilities param for firefox driver

.travis.chrome.sh, .travis.yml, travis-install.bash
Gets Google chrome to install on travis-ci.org
=> google chrome install

docs/drivers/chrome.rst, docs/drivers/phantomjs.rst
Update the documentation so it's obvious of how to use custom executable paths.
=> update custom driver docs

docs/index.rst, docs/tutorial.rst
I added a note to the index and tutorial page to let users know that firefox is the default driver.
=> add note that firefox is used by default

splinter/driver/webdriver/chrome.py
=> #513 remove incognito mode by default

splinter/driver/webdriver/__init__.py, splinter/driver/zopetestbrowser.py
=> initial suggestion for select_by_text instead of using value

docs/community.rst
Fix of salad project link - it has been moved
=> Links update

README.rst
Add new project links:
* pytest-splinter
* PyPOM
* pypom_form
=> update README project links (pytest-splinter, PyPOM and pypom_form)

splinter/driver/lxmldriver.py, tests/fake_django/urls.py, tests/fake_webapp.py, tests/form_elements.py, tests/static/index.html
I discovered that lxml driver doesn't include a value when a form is submitted by clicking a submit button.
I fixed it for Django and chrome clients. Other tests don't run on my machine for now. 
Please, let me know what do you think.
=> Include a submit button value when form submitted by clicking 

splinter/driver/webdriver/__init__.py
In reference to issue 555
Fixes #555
=> handle exceptions when calling quit on webdriver

docs/drivers/chrome.rst, docs/drivers/firefox.rst, splinter/driver/webdriver/firefox.py
Ref: https://github.com/SeleniumHQ/selenium/issues/3390
=> Add Firefox incognito mode.

docs/drivers/firefox.rst
missed a line break to make the code block display properly.
=> docs text fix

docs/http-proxies.rst, docs/index.rst
=> Documentation for HTTP proxy use

splinter/driver/lxmldriver.py
have created issue before. See https://github.com/cobrateam/splinter/issues/595
=> fix issue #595

docs/contribute/setting-up-your-development-environment.rst
docs/contribute/setting-up-your-development-environment.rst: update links, improve wording.
=> setting-up-your-development-environment.rst: wording, links

README.rst
- Inserted usage example replicated from official tutorial to illustrate the usefulness of this tool for new comers
- Uniformed the pattern of bullet list as well as capitalization along all sections to improve readability
- Fixed some small grammar errors for better precision in meanings
Please review for correctness
Thank you!
=> README.rst refinement

splinter/request_handler/status_code.py, tests/status_code.py
Provide solution for issue #460
=> Add __ne__ to the StatusCode class for Python 2.7.x compatibility

docs/drivers/installing_pyqt.rst
=> Minor language correction

docs/contribute/writing-new-drivers.rst
=> Minor text correction, slight changes to readability

splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/webdriver/cookie_manager.py, splinter/driver/zopetestbrowser.py
=> Fixed __eq__ not returning boolean value

splinter/driver/lxmldriver.py, splinter/driver/webdriver/__init__.py, splinter/driver/zopetestbrowser.py
this seems like a fix for #628
=> fix find_by_text chaining

splinter/driver/webdriver/__init__.py, tests/base.py
=> Browser.get_alert() now waits for alert to present

tests/static/index.html
This change prevents the page from scrolling to the top after the first click.
=> Fix test_double_click

splinter/element_list.py
=> ElementList is no longer a subclass of list

splinter/driver/webdriver/__init__.py
=> Do not implicitly rely on selector name

splinter/element_list.py, tests/test_element_list.py
=> ElementList now accepts slice objects

docs/iframes-and-alerts.rst, splinter/driver/webdriver/__init__.py, tests/iframes.py, tests/static/index.html
This mimics the functionality available in Selenium and solves #520
=> Allow browser.get_iframe() to accept a web element

splinter/driver/lxmldriver.py, splinter/driver/webdriver/__init__.py, splinter/driver/xpath_utils.py, splinter/driver/zopetestbrowser.py, tests/find_elements.py, tests/xpath_concat.py
=> find_by_text handles strings with quotation marks

docs/javascript.rst
Added an example how to use JavaScript to enter complex text through Splinter
=> How to fill in complex text values

docs/index.rst, docs/selenium-keys.rst, splinter/driver/__init__.py
Could I have missed something?
=> add in docs the possibility to use selenium #567

splinter/driver/webdriver/__init__.py, tests/base.py, tests/fake_webapp.py, tests/static/click_intercepted.html
Sometimes, an element may be covered by another, but only for a limited amount of time. This change adds a retry mechanism to a click attempt.
=> Retry WebElement.click if Exception is thrown

tests/base.py
Baby steps towards running tests in parallel
=> Refactor forward/back tests to run in isolation

docs/news/0.1.1.rst
=> Fix simple typo: compability -> compatibility

splinter/driver/webdriver/__init__.py
=> Fix unexpected keyword argument 'original_find'

docs/tutorial.rst
=> Update Google Search button name

.travis.yml, tests/base.py, tests/form_elements.py
They weren't actually ever running, as far as I can tell.
=> Fix django tests

test-requirements.txt
there are some security reports in the oldest version: https://github.com/advisories/GHSA-43fq-w8qq-v88h
=> upgrade Pillow to the latest version to avoid some security problems

.travis.yml, travis-install.bash
+ Reduce number of travis jobs to slightly improve speed
=> Remove unused block from travis-install.bash

docs/conf.py, splinter/driver/__init__.py, splinter/driver/lxmldriver.py, splinter/driver/webdriver/__init__.py, splinter/driver/zopetestbrowser.py, tests/form_elements.py, tests/test_zopetestbrowser.py
=> Add flag to ignore missing fields in fill_form

samples/test_google_search.py, splinter/browser.py, splinter/driver/djangoclient.py, splinter/driver/flaskclient.py, splinter/driver/lxmldriver.py, splinter/driver/webdriver/__init__.py, splinter/meta.py, test-requirements.txt, tests/form_elements.py, tests/popups.py, tests/test_djangoclient.py, tests/test_flaskclient.py, tests/test_zopetestbrowser.py
This PR makes the linting a bit stricter, but helps standardize the code. The places where it makes more sense to follow existing convention than fix style have been given #noqa comments to skip the linter.
=> Add more linting packages

setup.py
Fixes #886
Hi @strichter @andrewsmedina, how does this look?
Let me know if this needs any changes.
Thanks
=> Add license declaration in setup.py

splinter/driver/lxmldriver.py
Redo of #820 using six and with merge conflict addressed.
Fixes #819
=> Fix lxmldriver url join when form action is empty

docs/drivers/chrome.rst, docs/drivers/firefox.rst
+ Small rewrites of the sections
=> Nest WebDriver init arguments under the Using section

docs/drivers/django.rst, docs/drivers/flask.rst, docs/drivers/zope.testbrowser.rst
=> Exclude non-implemented methods from docs

requirements/test.txt, requirements/test_windows.txt, tox.ini
Don't specify dependencies that are already in setup.py
=> Cleanup unit test dependencies

setup.py
Makes it easier to open issues / change information
Example:
=> `setup.py`: Add project URLs for PyPI

docs/drivers/chrome.rst
Hello, as a newbie I would like to make my contribution to your repo as a suggestion: I noticed a the link to ChromeDriver says that it is about to expire and replaced it with the new one. 
Thank you.
=> Updated link soon to be deprecated.

docs/drivers/remote.rst
Added LambdaTest Remote Driver Code Sample
=> Added LambdaTest Remote Driver Code Sample

splinter/browser.py
Fixes https://github.com/cobrateam/splinter/issues/1052
=> [RFC] Do not require Selenium to be installed only for WebDriverException

splinter/browser.py
use named logger for splinter
closes #1054
=> Use named logger instead of root logger

.github/workflows/main.yml, .github/workflows/windows.yml, setup.py, tests/base.py, tests/get_browser.py, tests/test_browser.py, tests/test_webdriver.py, tox.ini
+ Tweak CI to run WD and non-WD tests separately. This better reflects real world environments.
=> Fix missing urllib3 dependency

.github/workflows/main.yml, .github/workflows/windows.yml, setup.py
=> Add Python 3.12 to CI

.readthedocs.yaml
This should fix our docs build.
=> Add the configuration for readthedocs

.github/workflows/macos.yml, .github/workflows/main.yml, .github/workflows/upload-to-pypi.yml, .github/workflows/windows.yml, .pre-commit-config.yaml, samples/test_facebook_events.py, splinter/driver/__init__.py, tests/fake_django/settings.py
- upgrade actions to clear warnings
- update pre-commit hooks and configuration
=> CI updates

.github/workflows/lint.yml, .github/workflows/macos.yml, .github/workflows/main.yml, .github/workflows/windows.yml, tox.ini
Handling a couple of points from #1256
=> Align tox and CI jobs

docs/cookies.rst, docs/install/external.rst, splinter/abc/cookie_manager.py, splinter/driver/__init__.py, splinter/driver/lxmldriver.py, splinter/driver/webdriver/__init__.py, splinter/driver/zopetestbrowser.py
+ Cleanup cookiemanager docs a bit
=> fix: Various errors when building docs
